sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t mmallimo/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true mmallimo/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-west-2-488870446623'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY